# render.yaml — FastAPI backend + Vite/React frontend (served by Node web)

services:
  # ------------------------- BACKEND (FastAPI) -------------------------
  - type: web
    name: stock-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FINNHUB_API_KEY
        sync: false
      - key: FINNHUB_SECRET
        sync: false
      - key: TWELVEDATA_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false

  # ------------------------- FRONTEND (Vite/React) -------------------------
  - type: web
    name: stock-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: |
      npm ci
      npm run build
    startCommand: npx serve -s dist -l $PORT
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE
        fromService:
          type: web
          name: stock-backend
          envVarKey: RENDER_EXTERNAL_URL
