# render.yaml — FastAPI backend + Vite/React frontend (static site)

services:
  # ------------------------- BACKEND (FastAPI) -------------------------
  - type: web
    name: stock-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      # Fill these in the Render UI after it creates the service
      - key: FINNHUB_API_KEY
        sync: false
      - key: FINNHUB_SECRET
        sync: false
      - key: TWELVEDATA_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false

  # ------------------------- FRONTEND (Vite/React) -------------------------
  - type: static_site
    name: stock-frontend
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    publishPath: dist

    # Single-page-app fallback so client routes work
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    # Optional: small cache header for static assets
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=60

    envVars:
      # Wire frontend -> backend automatically
      - key: VITE_API_BASE
        fromService:
          type: web
          name: stock-backend
          envVarKey: RENDER_EXTERNAL_URL
