# render.yaml — FastAPI backend (web) + Vite/React frontend (web serving static)

services:
  # ------------------------- BACKEND (FastAPI) -------------------------
  - type: web
    name: stock-backend
    env: python
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FINNHUB_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: TWELVEDATA_API_KEY
        sync: false

  # ------------------------- FRONTEND (Vite build served by Node) -------------------------
  - type: web
    name: stock-frontend
    env: node
    rootDir: frontend
    plan: free
    autoDeploy: true
    buildCommand: |
      npm ci
      npm run build
    # `serve -s` provides SPA history fallback, so client routes work
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE
        fromService:
          type: web
          name: stock-backend
          envVarKey: RENDER_EXTERNAL_URL
