# render.yaml — FastAPI backend + Vite/React frontend (static)

services:
  # ------------------------- BACKEND (FastAPI) -------------------------
  - type: web
    name: stock-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      # Add your real keys in the Render UI after the first deploy
      - key: FINNHUB_API_KEY
        sync: false
      - key: FINNHUB_SECRET
        sync: false
      - key: TWELVEDATA_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false

  # ------------------------- FRONTEND (Vite/React) -------------------------
  - type: static
    name: stock-frontend
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist

    # SPA fallback so client-side routes work
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    # Optional: small cache for all assets
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=60

    # Make Vite talk to the backend’s public URL at build time
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: stock-backend
          envVarKey: RENDER_EXTERNAL_URL
